### ISSUE TITLE
Question about layout

### ISSUE THREAD

**Issue by bentonmize** [osa1/Dextrack#4]
Sorry, not a real issue, just a question and I'm not sure how else to pose it to you 😄 .  I just got a Garmin (long time Fitbit Versa user before the SDKs got canned and you can't do dev on the platform anymore 😞 ), love the fonts and style your watch face has.  I've only started a new project, and was wondering why you chose to make the whole screen a Drawable as opposed to using individual layout elements etc. and setting fonts/positioning there?  Just a genuine question for someone who's trying to learn.  Awesome work!

**Comment by osa1** [comment]
Hi @bentonmize.

> was wondering why you chose to make the whole screen a Drawable as opposed to using individual layout elements etc. and setting fonts/positioning there?

It just felt easier, because location of the things I draw all depend on the locations of others. For example, (IIRC) the glucose data graph starts below the time, second is drawn right of HHMM text etc. I don't know how else to draw things with positions relative to each other, other than drawing all of them in the same drawable.

I'm a noob when it comes to Garmin apps so it's possible that I'm doing it wrong. If you know a better way let me know 😄
